// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcI9l6nhSMamVpZ6FqgTd2lIHJjDVc1_4',
    appId: '1:404147231743:web:bd4706ab3be1dfadb365ca',
    messagingSenderId: '404147231743',
    projectId: 'ff-proje-e7b5b',
    authDomain: 'ff-proje-e7b5b.firebaseapp.com',
    storageBucket: 'ff-proje-e7b5b.appspot.com',
    measurementId: 'G-5GWRNP9FFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIV0o3_gj1ZZ0-LShbdYGEB7wB9KZZQWc',
    appId: '1:404147231743:android:7b65d65a73030103b365ca',
    messagingSenderId: '404147231743',
    projectId: 'ff-proje-e7b5b',
    storageBucket: 'ff-proje-e7b5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5JoCc13D6anq5_V_bBaZcw4-bR2immng',
    appId: '1:404147231743:ios:ce09472543da00ccb365ca',
    messagingSenderId: '404147231743',
    projectId: 'ff-proje-e7b5b',
    storageBucket: 'ff-proje-e7b5b.appspot.com',
    iosBundleId: 'com.example.ffChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5JoCc13D6anq5_V_bBaZcw4-bR2immng',
    appId: '1:404147231743:ios:ce09472543da00ccb365ca',
    messagingSenderId: '404147231743',
    projectId: 'ff-proje-e7b5b',
    storageBucket: 'ff-proje-e7b5b.appspot.com',
    iosBundleId: 'com.example.ffChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcI9l6nhSMamVpZ6FqgTd2lIHJjDVc1_4',
    appId: '1:404147231743:web:5a1cb5fddb6bb525b365ca',
    messagingSenderId: '404147231743',
    projectId: 'ff-proje-e7b5b',
    authDomain: 'ff-proje-e7b5b.firebaseapp.com',
    storageBucket: 'ff-proje-e7b5b.appspot.com',
    measurementId: 'G-WYYS42NZR4',
  );
}
